# Generated by Django 4.2 on 2023-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_Achat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
